# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - SmartSuiteX

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: 'smartsuitex-website/shadcn-ui/package-lock.json'

      - name: Install dependencies
        working-directory: ./smartsuitex-website/shadcn-ui
        run: |
          npm ci

      - name: Build application
        working-directory: ./smartsuitex-website/shadcn-ui
        run: |
          npm run build

      - name: Run tests (if available)
        working-directory: ./smartsuitex-website/shadcn-ui
        run: |
          npm run test --if-present
        continue-on-error: true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./smartsuitex-website/shadcn-ui/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ smartsuitex-fegtdvcrhmfsfccw.centralus-01.azurewebsites.net }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List files for debugging
        run: |
          echo "Current directory contents:"
          ls -la
          echo "File structure:"
          find . -type f -name "*.html" -o -name "*.js" -o -name "*.css" | head -20
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SmartSuiteX'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}