# This workflow will build and push the SmartSuiteX website to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli#create-a-project-zip-file

name: Build and deploy SmartSuiteX to Azure Web App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'smartsuitex-app'    # set this to your SmartSuiteX app name
  AZURE_WEBAPP_PACKAGE_PATH: '.'         # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                   # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies (root)
      run: npm ci

    - name: Install dependencies (React app)
      run: cd smartsuitex-website/shadcn-ui && npm ci

    - name: Build SmartSuiteX React application
      run: cd smartsuitex-website/shadcn-ui && npm run build

    - name: Copy build files to deployment directory
      run: |
        mkdir -p deployment
        cp -r smartsuitex-website/shadcn-ui/dist/* deployment/
        cp web.config deployment/

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: deployment

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}